var ejs = require("ejs");
var pdf = require("html-pdf");
var path = require("path");
var config = require("../../config/config.js");
var fs = require("fs");


module.exports = {
  GenPDF: function (setData, fileName, callback) {
    let researcherCvFolder = "./public/file/cv";
    let folderName = researcherCvFolder.split("/");
    let folderNameTmp = ".";
    for (let i = 1; i < folderName.length; i++) {
      folderNameTmp = folderNameTmp + "/" + folderName[i];
      if (!fs.existsSync(folderNameTmp)) {
        fs.mkdirSync(folderNameTmp);
      }
    }
    ejs.renderFile(
      path.join(__dirname, "cv-template-2.ejs"),
      { objData: setData },
      (err, data) => {
        if (err) {
          console.log(err)
          var alert =
            "[func. GenPDF] Error in finding Researcher Error: " + err.message;
          callback("171", alert, null);
        } else {
          let savePath = researcherCvFolder + "/" + fileName + ".pdf";
          console.log(savePath);
          let options = {
            "format": "A4",
            "orientation": "portrait",
            "header": {
              "height": "20mm",
              "contents": '<div class="page-number" style="text-align: right;">{{page}}/{{pages}}</div>'
            },
            "footer": {
              "height": "20mm",
              "contents": {
                // first: 'Cover page',
                // 2: 'Second page', // Any page number is working. 1-based index
                default: `<div class="link-to-website" style="text-align: right;"><p>Generated by School of Science, KMITL, Research directory system platform. (Version 2.0)</p><p>More information <a class="underline" href="https://research.science.kmitl.ac.th/researcher/${setData.id}">https://research.science.kmitl.ac.th/researcher/${setData.id}</a></p></div>`,
                // last: 'Last Page'
              }
            },
          };
          // return response.send(data)
          pdf.create(data, options).toFile(savePath, function (error, data) {
            if (error) {
              var alert =
                "[func. GenPDF] Error in finding Researcher Error: " +
                error.message;
              callback("171", alert, null);
            } else {
              data = savePath.replace(
                /\.\/public/i,
                config.saveImagePath
                // `https://research.science.kmitl.ac.th/uploads`
              );
              callback("172", null, data);
            }
          });
        }
      }
    );
  },
};

//----------------
